---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-logger
  labels:
    app: json-logger
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: json-logger
  template:
    metadata:
      labels:
        app: json-logger
        env: prod
    spec:
      containers:
        - name: json-logger
          image: ghcr.io/gnur/jsonlogger:v1-1-gf4bc3b8
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
