# https://taskfile.dev

version: "3"

tasks:
  up:
    deps:
      - task: check-tools
    env:
      STARTTIME:
        sh: date +%s
    status:
      - talosctl cluster show --name inu-dev-cluster | grep -q "^NETWORK NAME\s*[^ ]"
    cmds:
      - |
        talosctl cluster create --name inu-dev-cluster 
      - talosctl config node 10.5.0.2
      - |
        end=$(date +%s)
        echo -e "\n>>>Cluster create took $((end-STARTTIME)) seconds"
  add-error:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/robusta-dev/kubernetes-demos/main/pending_pods/pending_pod_node_selector.yaml
      - kubectl apply -f bad-deployment.yaml

  down:
    deps:
      - task: check-tools
    env:
      STARTTIME:
        sh: date +%s
    cmds:
      - talosctl cluster destroy --name inu-dev-cluster
      - rm -rf talosconfig.yaml
      - kubectl config delete-cluster inu-dev-cluster || true
      - kubectl config delete-user admin@inu-dev-cluster || true
      - kubectl config delete-context admin@inu-dev-cluster || true
      - kubectl config unset current-context
      - |
        end=$(date +%s)
        echo -e "\n>>>Cluster delete took $((end-STARTTIME)) seconds"

  check-tools:
    run: once
    preconditions:
      - sh: command -v talosctl > /dev/null
        msg: "Make sure talosctl is installed and in your path (https://talos.dev/)."
      - sh: command -v kubectl > /dev/null
        msg: "Make sure kubectl is installed and in your path (https://downloadkubernetes.com/)."
