apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: jsonlogger
build:
  artifacts:
    - image: ghcr.io/gnur/jsonlogger
      platforms:
        - linux/arm64
      context: .
      ko:
        dependencies:
          paths:
            - '*.go'
            - go.*
