# https://taskfile.dev
# proudly influenced by Rio the Taskfile and k9s wizard

version: "3"

tasks:
  up:
    deps:
      - task: check-tools
    env:
      STARTTIME:
        sh: date +%s
    status:
      - talosctl cluster show --name dcnd-utrecht-demo | grep -q "^NETWORK NAME\s*[^ ]"
    cmds:
      - |
        talosctl cluster create --name dcnd-utrecht-demo 
      - talosctl config node 10.5.0.2
      - |
        end=$(date +%s)
        echo -e "\n>>>Cluster create took $((end-STARTTIME)) seconds"

  add-workload:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/robusta-dev/kubernetes-demos/main/pending_pods/pending_pod_node_selector.yaml
      - kubectl apply -f ./metrics-server.yaml
      - kubectl apply -f bad-deployment.yaml
      - kubectl apply -f json-logger-deployment.yaml
      - kubectl apply -f sleeppod.yaml
      - kubectl apply -f victoria-metrics.yaml
      - kubectl apply -f echoo.yaml

  down:
    deps:
      - task: check-tools
    env:
      STARTTIME:
        sh: date +%s
    cmds:
      - talosctl cluster destroy --name dcnd-utrecht-demo
      - rm -rf talosconfig.yaml
      - kubectl config delete-cluster dcnd-utrecht-demo || true
      - kubectl config delete-user admin@dcnd-utrecht-demo || true
      - kubectl config delete-context admin@dcnd-utrecht-demo || true
      - kubectl config unset current-context
      - |
        end=$(date +%s)
        echo -e "\n>>>Cluster delete took $((end-STARTTIME)) seconds"

  check-tools:
    run: once
    preconditions:
      - sh: command -v talosctl > /dev/null
        msg: "Make sure talosctl is installed and in your path (https://talos.dev/)."
      - sh: command -v kubectl > /dev/null
        msg: "Make sure kubectl is installed and in your path (https://downloadkubernetes.com/)."
